#!/bin/sh

# This script runs configure with debugging flags set. This is what I use during
# development; for release, I just let autotools pick the appropriate flags -
# note that these flags are specific to g++ so they must be in here and not in
# configure.ac, because that would require users to have g++.

# See http://stackoverflow.com/questions/4553735/gnu-autotools-debug-release-targets
# and http://stackoverflow.com/questions/11647208/where-to-add-a-cflag-such-as-std-gnu99-into-an-autotools-project

source ../common_flags.sh

../configure CPPFLAGS=-DDEBUG CXXFLAGS="-g -O0 $COMPILER_FLAGS"

